### ISSUE TITLE
plane.npy

### ISSUE THREAD

**Issue by YLongJin** [y-u-a-n-l-i/Climate_NeRF#10]
how to got custom plane.npy？

**Comment by Abbsalehi** [comment]
@YLongJin you can find it in readme file

**Comment by chih-hao-lin** [comment]
Hi, in order to estimate plane parameters for customized data, you could use `utility/vanishing_point.py`, and run following script:
```
python -m utility.vanishing_point --dataset <DATASET_TYPE> -root_dir <DATA_ROOT> -output plane.npy
```
Please note that you might need to write customized dataloader and specify with `--dataset` argument
