### ISSUE TITLE
How to compute "plane.npy"?

### ISSUE THREAD

**Issue by Abbsalehi** [y-u-a-n-l-i/Climate_NeRF#14]
How to compute "plane.npy" for my own data?

**Comment by chih-hao-lin** [comment]
Hi, in order to estimate plane parameters for customized data, you could use `utility/vanishing_point.py`, and run following script:
```
python -m utility.vanishing_point --dataset <DATASET_TYPE> -root_dir <DATA_ROOT> -output plane.npy
```
Please note that you might need to write customized dataloader and specify with `--dataset` argument
