### ISSUE TITLE
ERROR: No matching distribution found for pynvrtc

### ISSUE THREAD

**Issue by cici19850** [y-u-a-n-l-i/Climate_NeRF#19]
when I excute pip install pynvrtc,The following error occurs:

ERROR: Ignored the following yanked versions: 7.0, 7.5, 8.0, 9.0, 9.1, 9.2
ERROR: Could not find a version that satisfies the requirement pynvrtc (from versions: none)
ERROR: No matching distribution found for pynvrtc

Looking forward to your reply, thank you.

**Comment by Rebeckamartensson** [comment]
How did you solve this? I have the same problem

**Comment by hyylyf** [comment]
Have you solved this problem? I've met the same problem too.
