### ISSUE TITLE
Controllability of the snow effect

### ISSUE THREAD

**Issue by Jumponthemoon** [y-u-a-n-l-i/Climate_NeRF#23]
Hi,

I'm wondering how to control the level of the snow effect?

**Comment by cici19850** [comment]
> I'm wondering how to control the level of the snow effect

Can you reproduce the effect of snow? Using Colmap's Garden Data

**Comment by Jumponthemoon** [comment]
> > I'm wondering how to control the level of the snow effect
> 
> Can you reproduce the effect of snow? Using Colmap's Garden Data

I used the Kitti scene, didn't try the Garden one. And i'm not really sure i produced the snow ball correctly because i felt like it was only stylized and not many snow accumulated on the object surface. What about you?

**Comment by Jumponthemoon** [comment]
> > > I'm wondering how to control the level of the snow effect
> > 
> > 
> > Can you reproduce the effect of snow? Using Colmap's Garden Data
> 
> I used the Kitti scene, didn't try the Garden one. And i'm not really sure i produced the snow ball correctly because i felt like it was only stylized and not many snow accumulated on the object surface. What about you?

@cici19850

**Comment by cici19850** [comment]
> used the Kitti scene, didn't try the Garden one. And i'm not really sure i produced the snow ball correctly because i felt like it was only stylized and not many snow accumulated on the object surface. What about you?

I used garden data but failed to reproduce the effect of snow,  I don't know why rendering everything black. What are the version numbers of CUDA and PyTorch Lightning that you have installed? I am using CUDA118 and PyTorch Lightning 1.9.5, and I am not sure if it is due to a version number issue that caused my rendering to fail

**Comment by Jumponthemoon** [comment]
> > used the Kitti scene, didn't try the Garden one. And i'm not really sure i produced the snow ball correctly because i felt like it was only stylized and not many snow accumulated on the object surface. What about you?
> 
> 
> 
> I used garden data but failed to reproduce the effect of snow,  I don't know why rendering everything black. What are the version numbers of CUDA and PyTorch Lightning that you have installed? I am using CUDA118 and PyTorch Lightning 1.9.5, and I am not sure if it is due to a version number issue that caused my rendering to fail

I'm not really sure if it is the version problem. But my setting is align with the official setting :CUDA11.3 and PyTorch lightning 1.7. 

Btw did you stylize it?
