### ISSUE TITLE
 RuntimeError: expected scalar type Float but found Half

### ISSUE THREAD

**Issue by wtj-zhong** [y-u-a-n-l-i/Climate_NeRF#3]
Thank you for your work. When I run the code python train.py --config /home/alex/Climate_NeRF/configs/Garden.txt --exp_name playground --root_dir $DATA_ROOT --sem_conf_path $SEM_CONF --sem_ckpt_path $SEM_CKPT, I encounter this error. Can you tell me the reason for the error?

 python train.py --config /home/alex/Climate_NeRF/configs/Garden.txt --exp_name playground  --root_dir $DATA_ROOT --sem_conf_path $SEM_CONF --sem_ckpt_path $SEM_CKPT
GridEncoding for spital: Nmin=16 b=1.58740 F=2 T=2^19 L=16
GridEncoding for RGB: Nmin=16 b=1.25057 F=2 T=2^19 L=32
rgb_input_dim: 80
GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
IPU available: False, using: 0 IPUs
HPU available: False, using: 0 HPUs
Load segmentation model from /home/alex/Climate_NeRF/CHECK/segformer_mit-b5_8x1_1024x1024_160k_cityscapes_20211206_072934-87a052ec.pth
Loads checkpoint by local backend from path: /home/alex/Climate_NeRF/CHECK/segformer_mit-b5_8x1_1024x1024_160k_cityscapes_20211206_072934-87a052ec.pth
scene up tensor([-0.0017, -0.8823, -0.4706])
scene scale 4.495019486110887
Loading 161 train images ...
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 161/161 [00:49<00:00,  3.23it/s]
Load segmentation model from /home/alex/Climate_NeRF/CHECK/segformer_mit-b5_8x1_1024x1024_160k_cityscapes_20211206_072934-87a052ec.pth
Loads checkpoint by local backend from path: /home/alex/Climate_NeRF/CHECK/segformer_mit-b5_8x1_1024x1024_160k_cityscapes_20211206_072934-87a052ec.pth
scene up tensor([-0.0017, -0.8823, -0.4706])
scene scale 4.495019486110887
Loading 24 test images ...
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 24/24 [00:07<00:00,  3.26it/s]
Loading 185 camera path ...
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 185/185 [00:00<00:00, 501.26it/s]
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]
Epoch 0:   0%|                                                                                                                                                  | 0/1000 [00:00<?, ?it/s]Traceback (most recent call last):
    return F.linear(input, self.weight, self.bias)
RuntimeError: expected scalar type Float but found Half

**Comment by y-u-a-n-l-i** [comment]
Thanks for your interest in our project. Can https://github.com/NVlabs/tiny-cuda-nn/issues/51 solve your problem(which is also mentioned in our environment setup)? In our project, we built tiny-cuda-nn in float32 to avoid nan errors during training.

**Comment by wtj-zhong** [comment]
Thank you for your reply, NVlabs/tiny-cuda-nn#51 can solve my problem
