### ISSUE TITLE
hardware requirements

### ISSUE THREAD

**Issue by LIUXIN4558** [y-u-a-n-l-i/Climate_NeRF#4]
Thank you very much for the author's sharing.

But may I ask if this code can be replicated using NVIDIA RTX 3080Ti with 12GB of memory?

**Comment by y-u-a-n-l-i** [comment]
Thanks for your interest! You can try to reduce `batch_size` in our config during scene reconstructions. During rendering, you can also reduce `chunk_size` for lower GPU memory consumption.
