### ISSUE TITLE
Can I run this project on my PC with a Windows10 ?

### ISSUE THREAD

**Issue by whisperwind-xue** [y-u-a-n-l-i/Climate_NeRF#5]
Can I run this project on my PC with a Windows10  ? Have you tested it on Windows? Thanks for your answer.

**Comment by y-u-a-n-l-i** [comment]
Thanks for your interest! Sorry, I didn't try our code on Windows. But if you install conda, cuda, etc. in Windows and have an Nvidia-GPU-equipped PC, our code might work. Also, I'm not sure whether our dependencies will work properly on Windows.

**Comment by Abbsalehi** [comment]
@whisperwind-xue you can try on Docker
