### ISSUE TITLE
the nan values during training ipdb

### ISSUE THREAD

**Issue by hjlstudy666** [y-u-a-n-l-i/Climate_NeRF#6]
thanks for your work!
during training, ipdb find the nan values:

sigmas contains nan
grads contains nan
normals_raw contains nan
normals_pred contains nan
nan in results[sigma]
nan in results[opacity]
nan in results[depth]
nan in results[rgb]
nan in results[normal_pred]
nan in results[semantic]
nan in results[ws]
nan in results[Ro]
nan in results[Rp]

I want to know how to solve this problem, thank you very much!

**Comment by y-u-a-n-l-i** [comment]
In which scene did you get nan issues? Could you provide more information about your environment? During my experiments, I mainly solved nan issues by compiling tiny-cuda-nn in float32.

**Comment by hjlstudy666** [comment]
Thank you very much, I found out that it was the tinycudann precision issue, I didn't install it properly before, now it's fixed.
